assets:
  - name: bootstrap
    url: http://getbootstrap.com/2.3.2/assets/bootstrap.zip
  - name: jqueryui
    url: https://github.com/jquery/jquery-ui/archive/master.zip
  - name: glyphicons
    url: http://glyphicons.com/files/glyphicons_free.zip
  - name: json2
    url: https://raw.github.com/douglascrockford/JSON-js/master/json2.js
  - name: twitter-text-js
    url: https://raw.github.com/twitter/twitter-text-js/master/twitter-text.js
  - name: jquery-themes
    url: http://jqueryui.com/resources/download/jquery-ui-themes-1.10.3.zip
directories:
  - conf
  - docs
  - lib
  - lib/public
  - lib/public/css
  - lib/public/img
  - lib/public/js
  - lib/views
  - lib/@
  - spec
files:
  - template: Gemfile.erb
    destination: . 
  - template: Rakefile.erb
    destination: .
  - template: version.rb.erb
    destination: lib/@
  - template: main.rb.erb
    destination: lib

